/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 22-Mar-2018 15:38:32 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS 'Category'
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

CREATE TABLE 'Category'
(
    'CategoryID' TEXT NOT NULL,
    'ParentID' TEXT,
	'CategoryName' TEXT NULL,
	'CategoryLevel' TEXT NULL,
	'BestOfferEnabled' TEXT NULL,
	'AutoPayEnabled' TEXT NULL,
    PRIMARY KEY('CategoryID'),
	CONSTRAINT 'FK_CategoryParentID' FOREIGN KEY ('ParentID') REFERENCES 'Category' ('CategoryID') ON DELETE No Action ON UPDATE No Action
)
;

/* Create Indexes */

CREATE INDEX 'IXFK_Category_Category'
 ON 'Category' ('CategoryID' ASC)
;
